### PR TITLE
Backlog 14

### PR DESCRIPTION
**Pull request by jameswhang**
- Added a way to play sound from the Raspberry Pi client
- Confirmed that it works

Caution: When you test this, turn your volume up in the Pi to max, otherwise you won't hear anything.

### CODE REVIEW

**Comment by jameswhang** [comment]
@cobrien7 Can you take a look at this? Thanks

**Comment by cobrien7** [comment]
Looks good - the sound plays on the pi when I run it.
We don't want to merge it as is though, right? Shouldn't main call ring(), and ring() call play_sound() ?

**Comment by jameswhang** [comment]
Yeah one sec, I realized that I can actually merge this ticket with another ticket (backlog 19). I'll let you know when I get that part done as well.

**Comment by jameswhang** [comment]
@cobrien7 Can you review this sometime?

**Comment by cobrien7** [comment]
Looks good to me

**Pull request merged**
