### PR TITLE
added the device settings page

### PR DESCRIPTION
**Pull request by jameswhang**
- User can set their own number
- Probably will have to add a way to link mobile to the right Pi here but will make that a separate ticket
- @jb08 Please review, thanks!

### CODE REVIEW

**Comment by jb08** [comment]
I just saw this... will code review shortly.

**Comment by jb08** [comment]
screen shot 2016-05-17 at 12 28 47 pm

**Comment by jb08** [comment]
it _works_ , but I don't quite get what it does or what user story it's aligned to. ok to merge and let's talk about it this afternoon before client meeting.

**Comment by jameswhang** [comment]
It's updating your own phone number. Otherwise there's no info of which number to text to in the db.

**Comment by jb08** [comment]
ok!

**Pull request closed without merging**
