### PR TITLE
Backlog 23

### PR DESCRIPTION
**Pull request by cobrien7**
This branch does the following
-Fully syncs the "Silence mode" toggle and time picker with the backend - so they write directly to the Pi settings as well as reading from them.
-Hides the dropdown menu for choosing durations when silence mode is on, as Rich asked for last week
@jameswhang can you review?

### CODE REVIEW

**Comment by jameswhang** [comment]
Looks good. Go ahead and merge please

**Comment by jb08** [comment]
this is really good - duration only showing when off, toggle at top a getter and a setter - nice job Connor.

**Comment by jb08** [comment]
screen shot 2016-05-24 at 3 42 06 pm

**Comment by jb08** [comment]
two things for future iterations: i) aligning time on iOS ; if change time, it persists to backend -- however, if then click "Go Silent" it changes to 1hr from current time; that's not a bug, but it may be confusing for user.

**Pull request merged**
