### PR TITLE
Make silence settings page display current mode and expiration time

### PR DESCRIPTION
**Pull request by cobrien7**
The UI only reads the database right now, you can't use the toggle or time field to change any settings, but we can add logic to isOn() and getExpTime() to change that if we want.
@jameswhang can you review this? Let me know how the time field looks on your phone, I had to mess with the CSS to make it look right and I don't know if alignment/size stuff will get messed up on other devices

### CODE REVIEW

**Comment by jameswhang** [comment]
@cobrien7 Thanks for working on this. It looks good, except the alignment gets messed up a little.

**Comment by cobrien7** [comment]
Is the alignment just that the "Duration" box is a different width from the first two? That's an easy fix if so. If not, could you post a screenshot here or on Slack when you get a chance?

**Comment by jameswhang** [comment]
screen shot 2016-05-15 at 7 54 06 pm

**Comment by jameswhang** [comment]
It looks like the "Silent Until:" has some alignment issues when you put a text and a dropdown button like that.. Is that dropdown necessary?

**Comment by cobrien7** [comment]
OK, for now we just removed the dropdown button - but when we connect the timepicker to the backend, we'll want to figure out some sort of affordance to show that it's a control and not just a display field.
I'll go ahead and merge since that was the only issue

**Pull request merged**
