### PR TITLE
Backlog-6 Contact pages

### PR DESCRIPTION
**Pull request by Danqi7**
1)show contacts on the silence view page
2)add new contacts

@cobrien7  can you please review it when you have time?

### CODE REVIEW

**Comment by cobrien7** [comment]
I think line 16 of application.js should be .once() instead of .on() - other than that it looks good to me

**Comment by Danqi7** [comment]
@cobrien7 I tried .once() but it doesn't seem to work. I think .on() would be fine in this case because whenever the contact button is clicked, the contact list is initialized to empty. What do you think?

**Comment by cobrien7** [comment]
It may not end up being a problem in practice, but I think there's still a race condition if you hit the button again and set it to empty before the first set of callbacks finishes executing - you could end up with duplicate contacts. 
Is there a reason you couldn't query the entire contacts object, loop over it to push the keys into a local list variable, and then point $scope.contacts at that list once the loop finishes? That way 2 different executions of getContacts() never push to the same list.

**Comment by Danqi7** [comment]
@cobrien7  assigned local var to $scope.var to avoid race condition

**Comment by cobrien7** [comment]
Looks good!

**Pull request merged**
